package com.techgem.account.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBTable(tableName = "account")
public class Account {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String accountId;
    @DynamoDBAttribute
    private String accountDescription;
    @DynamoDBAttribute
    private String status;
    @DynamoDBAttribute
    private String dtCreated;


}
