# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3
  aws-ecs: circleci/aws-ecs@2.0.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0-node
    steps:
      - checkout
      - run:
          name: Building Spring Boot Jar
          command: mvn -B -DskipTests clean package
      - run:
          name: Running JUnit Test Cases
          command: mvn test
      - run:
          name: Sonar Analysis
          command: mvn verify sonar:sonar -Dsonar.projectKey=techgem1986_account-service
      - run:
          name: Docker Login
          command: docker login -u $DOCKER_ID -p $ACCESS_TOKEN
      - run:
          name: Building Container Image
          command: mvn clean compile jib:build -Dimage=techgem1986/account-service:$CIRCLE_BUILD_NUM

workflows:
  build-deploy:
    jobs:
      - build:
          context:
            - SonarCloud
            - DockerHub
      - aws-ecs/deploy-service-update:
          cluster-name: 'techgem1986'
          container-image-name-updates: 'container=account-service,image-and-tag=docker.io/techgem1986/account-service:latest'
          family: 'account-service'
          requires:
            - build
          context:
            - AWS